### ISSUE TITLE
Missing `null` writes when writing `Object[]` values

### ISSUE THREAD

**Issue by georgewfraser** [FasterXML/jackson-dataformat-csv#116]
When writing arrays to CSV, if there is a null, columns get written out of order. Reproduced in 2.7.1 with this test: https://gist.github.com/georgewfraser/164647fbaca61aadf9ee

Possibly related to https://github.com/FasterXML/jackson-dataformat-csv/issues/68

**Comment by cowtowncoder** [comment]
Thank you for reporting this, providing test case. Hope to look into this soon.

**Comment by cowtowncoder** [comment]
I can reproduce this locally; looks like "all nulls" somehow does not work as expected.

**Comment by cowtowncoder** [comment]
More likely related to #106.

**Comment by cowtowncoder** [comment]
This may be tricky to fix. The problem is that suppression serves a function (2 tests fail if it's removed), but I hope there's a way to refine heuristics further to support all usage -- perhaps by further separating output of the first column or something like that (and not just by "array in array" structure).

**Comment by cowtowncoder** [comment]
moved: https://github.com/FasterXML/jackson-dataformats-text/issues/10
