### ISSUE TITLE
Add `CsvGenerator.Feature` to fail if linefeeds included in quoted content

### ISSUE THREAD

**Issue by balbusm** [FasterXML/jackson-dataformat-csv#118]
I'm writing the app that should ignore invalid lines in CSV.  In the below example  I would expect that all lines are printed or at least line 2 and 3 is printed, but currently I'm getting exception and nothing is printed.
Code:

```
CsvSchema schema = CsvSchema.emptySchema().withHeader();
FileReader fileReader = new FileReader(file);
MappingIterator<Map<String,String>> it = mapper.readerFor(Map.class)
  .with(schema)
  .readValues(fileReader);
while (it.hasNext()) {
  try {
    Map<String,String> rowAsMap = it.next();
    System.out.println(rowAsMap);
  } catch (Exception e) {
    System.out.println(e);
  }
}
```

Example input:   

```
1,Head2,Head3,Head4,"Head5
2,Head2,Head3,Head4,Head5
3,Head2,Head3,Head4,Head5
```

**Comment by cowtowncoder** [comment]
Hmmh. Unfortunately I am not sure this is possible: since linefeeds are acceptable within quoted content, the last value would enclose lines 2 and 3. So although recovery should be able to recover from missing end quote, that would not help a lot given that the one logical line that exists would be skipped. 

One possibility here would be addition of the CSV read feature, or possible a `CsvSchema` property, which would enable/disable ability to contain linefeeds within quoted content.

**Comment by balbusm** [comment]
I agree, disabling quoted content with linefeeds makes sens.

**Comment by cowtowncoder** [comment]
Another question would be that of what to do with linefeeds: convert to spaces, drop, or throw exception. I assume first (spaces) or last (exception) are most likely actions.

**Comment by cowtowncoder** [comment]
moved: https://github.com/FasterXML/jackson-dataformats-text/issues/11
