### ISSUE TITLE
Add methods for appending columns of a `CsvSchema` into another

### ISSUE THREAD

**Issue by sharpau** [FasterXML/jackson-dataformat-csv#142]
Currently if I am building a CsvSchema with columns from a POJO and some other custom columns, I have to first build a CsvSchema from the POJO, and then provide the columns from that schema to a second CsvSchema.Builder. It's not a huge deal, but it seems like it'd be a nice improvement.

Current situation:
```
        CsvMapper mapper = new CsvMapper();
        CsvSchema pojoSchema = mapper.schemaFor(Pojo.class);

        CsvSchema fullSchema = CsvSchema.builder()
                .addColumns(pojoSchema)
                .addColumns(otherProperties, CsvSchema.ColumnType.STRING)
                .build().withHeader().withNullValue("");
```

Desired situation:

```
        CsvMapper mapper = new CsvMapper();

        CsvSchema fullSchema = CsvSchema.builder()
                .addColumnsFromPojo(Pojo.class)
                .addColumns(otherProperties, CsvSchema.ColumnType.STRING)
                .build().withHeader().withNullValue("");
```

**Comment by cowtowncoder** [comment]
While I understand why it would be convenient, I am not sure it is feasible because actual schema generation requires knowledge that only `ObjectMapper` has (and/or perhaps `ObjectReader` or `ObjectWriter`) -- basically information equivalent to knowing how to serialize a POJO.
It might be possible to add `ObjectMapper` argument.

**Comment by cowtowncoder** [comment]
Added `CsvSchema.withColumnsFrom(CsvSchema)` and `CsvSchema.Builder.addColumnsFrom(CsvSchema)` methods which should help here.
It is unfortunately not possible to pass just type (`Class`, `JavaType`) since these objects do not have proper execution context (`ObjectMapper` or `ObjectWriter`) for introspection; but I think this should be helpful enough considering that mapper/writer is needed for initial introspection anyway.
