### ISSUE TITLE
MappingIterator does not clear current token after exception

### ISSUE THREAD

**Issue by flappingeagle** [FasterXML/jackson-dataformat-csv#52]
I want to read a whole CSV-File and want it to be mapped to a list of pojos.
But if there are any unmappable fields (example: csv-file contains column-value "1.280" but the field in the pojo is of type integer) the reading should not abort but should simply ignore this line.
The MappingIterator can be used, but does not handle the exception very well (in my opinion) which even leads to an endless loop. I can handle this problem if i clear the current token outside:
```java
        MappingIterator<LineDTO> values = csvReader.readValues(importStream);
        List<LineDTO> lines = new ArrayList<>();
        while (values.hasNextValue()) {
            try {            
                LineDTO line = values.nextValue();
                lines.add(line);                
            } catch (Exception e) {
                // bug in jackson, jackson does not clear the token in error-case.
                values.getParser().clearCurrentToken();
            } 
        }
```
But in my opinion it would be better if a call to "nextValue" always clears the current token?

regards and greetings,
bernd

**Comment by cowtowncoder** [comment]
For what it is worth, I think this is superceded by:

https://github.com/FasterXML/jackson-databind/issues/734

and 2.5.2 specifically has a fix to ensure that current token, at least, is cleared even if exception is thrown (not doing that was causing potential infinite loop, where iterator was not advancing).
Clearing the token will prevent stuck processing, although without other changes may expose partial/duplicate lines so that caller may see one line "split" in one more than one pieces. 

Going forward, if 734 for databind gets implemented, it should be possible to have safer recover available.
