### ISSUE TITLE
Support Comment Features

### ISSUE THREAD

**Issue by nezda** [FasterXML/jackson-dataformat-csv#56]
It would be useful if `Feature.ALLOW_YAML_COMMENTS` were supported (probably `Feature.ALLOW_COMMENTS` for consistency sake).

**Comment by cowtowncoder** [comment]
After reading documentation I could find, I further limited this so that only '#' as the first character of a line counts as a comment; this may be relaxed in future if it turns out necessary.
Also verified that leading '#' will lead to values being quoted on writing.

**Comment by cowtowncoder** [comment]
Implemented, will be in 2.5.0.

**Comment by nezda** [comment]
I really appreciate your work on this, though I can't ditch my hand rolled solution without the comments-anywhere feature as I have a raft of existing data.  Should I open a separate feature request issue?

**Comment by cowtowncoder** [comment]
Yes, please open a separate issue.

Adding handling in beginning of a column 
(i.e. at beginning of line, or following column separator) is relatively easy; I actually started this way, but since almost all examples I saw assumed comment-starting-from-first-char, I chose a bit more conservative initial implementation.
