### ISSUE TITLE
Quotes in Header sometimes exist and sometimes not

### ISSUE THREAD

**Issue by arnzel** [FasterXML/jackson-dataformat-csv#64]
I have the following Pojo

     public class Pojo{
    ..
    private String produktInfo;
	
	private String produktInfo2;
    ..
    }

I create an Csv for this pojo with the following code

    Pojo pojo = ...
    CsvMapper mapper = new CsvMapper();
    CsvSchema schema = mapper.schemaFor(Pojo.class).withColumnSeparator(';').withHeader().withLineSeparator("\n");

    ObjectWriter writer = mapper.writer(schema);
		
    writer.writeValue(new File(interessent.getAuftragsnummer() + ".csv"), pojo);

The csv file hast the following Header

...produktInfo;"produktInfo2"...

I dont understand why produktInfo2 hat quotes and produktInfo not

**Comment by cowtowncoder** [comment]
It is probably due to checks using a threshold, so that for long enough text values, quotes are used without checking, instead of scanning through the string to make sure they are needed. Since quotes may or may not be used, heuristics are used by default; both approaches works.

But if you want strict checking for need of quoting, you can enable `CsvParser.Feature.STRICT_CHECK_FOR_QUOTING` on `CsvFactory`. That will guarantee that check is made using full String regardless of its length.
