### ISSUE TITLE
Is there any way to handle multi JsonMapperException for each lines?

### ISSUE THREAD

**Issue by tasuku-s** [FasterXML/jackson-dataformat-csv#88]
Hi, I wrote the code of mapping from uploaded CSV file to POJO list using schema for POJO.
And I would like to respond with sensible error information, such as line number and column name for each columns of for each lines when rising `JsonMappingException` from deserializers.
But I couldn't find any option or setting to handle more than two errors for each lines.
Is there any way to handle these?

**Comment by cowtowncoder** [comment]
Just to make sure I understand the question: are you hoping to continue binding data into POJOs, even if one of the lines has a problem that is indicated using an exception?

If so, `MappingIterator` obtained via `ObjectRead.readValues()` does allow recovery in Jackson 2.6.0, so that it is possible to try to read more values even after the first exception. There is always a possiblity that underlying state machine gets into an odd state for some decoding issues; but for simple mapping problems (unrecognized property), recovery should work.

If you are instead hoping to find out if there are multiple problems on a single row, this is not currently possible.

**Comment by tasuku-s** [comment]
I would like to find out if there are multiple problems on a single row.
Thanks.
