### ISSUE TITLE
Escape char is not being escaped during serialization

### ISSUE THREAD

**Issue by cloudyday** [FasterXML/jackson-dataformat-csv#98]
Hello everyone,

I use \ as an escape char and some of my string values have \ at the end. During serialization \ is not being escaped and transformed to \\\ as it is expected by me. 

The result is that the quotation mark at the end of the serialized csv column is now being treated as a literal character and not as my quote char during deserialization.

Thanks.

**Comment by cowtowncoder** [comment]
Have you configured `CsvSchema` to use quoting with `\` character? Escaping is not enabled by default as it is not part of standard CSV format, but an extension.

**Comment by cloudyday** [comment]
My quote char is `"` and my escape char is `\`.

During serialization a string like  
> foo bar\

will get serialized to

> "foo bar\"

as opposed to what I expect, which is:

> "foo bar\\\"

During deserialization, the quote character is interpreted as literal which destroys the csv row.

**Comment by cowtowncoder** [comment]
Ok. Serialization part sounds like a bug. Is this with version 2.6.3?

**Comment by cloudyday** [comment]
Yes. Version 2.6.3.

Can you reproduce it?

**Comment by cowtowncoder** [comment]
I haven't had time yet, will try to reproduce now.

**Comment by cowtowncoder** [comment]
Yes, I can reproduce this. And looks like the underlying reason is that encoder does not actually consider escape character at all -- only decoder (parser) has special handling. So that's the first thing to fix.

Another related question is whether quote character should be escaped with escape character, or with the doubling mechanism. But first things first, ensure that escape character itself is escaped by doubling it.
